# fly.toml app configuration file generated for kisumuruby on 2026-04-26T06:56:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kisumuruby'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 9292
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
